<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>DaJet.Compiler</AssemblyName>
    <RootNamespace>DaJet.Compiler</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>Zhichkin</Authors>
    <Description>DaJet Script Compiler</Description>
    <Copyright>Zhichkin © 2026</Copyright>
    <PackageProjectUrl>https://zhichkin.github.io/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/zhichkin/dajet/tree/main/src/dajet-compiler</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DaJet.Metadata" Version="5.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dajet-scripting\dajet-scripting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="scripts\select_derived.djs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\select_simple_join.djs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\select_simple.djs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="scripts\select_union_property.djs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
