<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DaJet.Host</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>DaJet.Host</AssemblyName>
    <Title>DaJet.Host</Title>
    <Version>1.0.10</Version>
    <Authors>Zhichkin</Authors>
    <Description>DaJet Script hosting service</Description>
    <Copyright>Zhichkin © 2026</Copyright>
    <PackageProjectUrl>https://zhichkin.github.io/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/zhichkin/dajet-scripting</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\dajet-interpreter\dajet-interpreter.csproj" />
  </ItemGroup>

</Project>
