using DaJet.Data;
using DaJet.Scripting.Model;
using DaJet.TypeSystem;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using System.Data;
using System.Text;

namespace DaJet.Scripting
{
    public sealed class MsBulkInsertProcessor : ProcessorBase
    {
        private readonly ScriptContext _context;
        private readonly InsertStatement _statement;
        private readonly EntityDefinition _target;
        private readonly int _yearOffset;
        private readonly Func<object, object> _convertDateTime;
        private readonly string _bufferName;
        private readonly string _bufferItem;
        private string _createType;
        private string _dropType;
        private string _insertTable;
        private readonly Dictionary<ColumnDefinition, int> _ordinals = new();
        private readonly Dictionary<ColumnDefinition, Func<object, object>> _converters = new();
        public MsBulkInsertProcessor(in ScriptContext context, in InsertStatement statement)
        {
            if (context.GetDataSource() is not MsDataSourceScope)
            {
                throw new InvalidOperationException();
            }

            _context = context;
            _statement = statement;
            _yearOffset = statement.YearOffset;

            if (_statement.Target is not TableReference table || table.Binding is not EntityDefinition target)
            {
                throw new InvalidOperationException();
            }

            if (_statement.Source is not VariableReference variable
                || variable.Binding is not DeclareStatement declare
                || !(declare.Type.IsArray && declare.Type.IsObject))
            {
                throw new InvalidOperationException();
            }

            _target = target;

            _bufferName = variable.Identifier;
            _bufferItem = string.Format("{0}{1}", _bufferName, "_Item");

            _context.CreateVariable(in _bufferItem);
            
            _convertDateTime = ConvertDateTimeWithOffset;

            TranspileInsertStatement();

            PrepareTableType();
        }
        private object ConvertDateTimeWithOffset(object value)
        {
            return MsDataMapper.ConvertDateTime(value, _yearOffset);
        }

        private SqlDataRecord _record;
        private void PrepareTableType()
        {
            List<SqlMetaData> columns = new();

            columns.Add(new SqlMetaData("order_column", SqlDbType.Int));

            PropertyDefinition property;
            List<PropertyDefinition> properties = _target.Properties;

            for (int p = 0; p < properties.Count; p++)
            {
                property = properties[p];

                PrepareTableTypeColumns(in property, in columns);
            }

            SqlMetaData[] metadata = columns.ToArray();

            _record = new SqlDataRecord(metadata);
        }
        private void PrepareTableTypeColumns(in PropertyDefinition property, in List<SqlMetaData> columns)
        {
            int ordinal = columns.Count;

            if (_statement.TryGetMapping(property.Name, out ColumnExpression map))
            {
                if (map.Expression is FunctionExpression function && function.Token == Token.VECTOR)
                {
                    ColumnDefinition column = property.Columns[0];

                    SqlMetaData metadata = new(column.Name, SqlDbType.Int);

                    columns.Add(metadata);

                    _ordinals.Add(column, ordinal++);
                    
                    //FIXME: _converters.Add(column, GetRowNumber);

                    return; // generated by SEQUENCE
                }
                else if (map.Expression is MemberAccessExpression member && member.GetVariableName() == _bufferName)
                {
                    member.Identifier = member.Identifier.Replace(_bufferName, _bufferItem);
                }
            }

            DataType input = property.Type;

            foreach (ColumnDefinition column in property.Columns)
            {
                if (column.IsGenerated)
                {
                    continue; // database auto-generated column
                }

                SqlDbType type = SqlDbType.Binary;
                Func<object, object> converter = null;

                if (column.Purpose == ColumnPurpose.Value)
                {
                    if (input.IsBoolean) { converter = MsDataMapper.ConvertBoolean; }
                    else if (input.IsDecimal) { converter = MsDataMapper.ConvertNumeric; type = SqlDbType.Decimal; }
                    else if (input.IsInteger) { converter = MsDataMapper.ConvertNumeric; type = SqlDbType.Decimal; }
                    else if (input.IsDateTime) { converter = _convertDateTime; type = SqlDbType.DateTime2; }
                    else if (input.IsString)
                    {
                        converter = MsDataMapper.ConvertString;
                        
                        type = (column.Type.IsFixed) ? SqlDbType.NChar : SqlDbType.NVarChar;
                    }
                    else if (input.IsBinary) { converter = MsDataMapper.ConvertBinary; type = SqlDbType.VarBinary; }
                    else if (input.IsUuid) { converter = MsDataMapper.ConvertUuid; }
                    else if (input.IsEntity) { converter = MsDataMapper.ConvertIdentity; }
                }
                else if (column.Purpose == ColumnPurpose.Tag) { converter = MsDataMapper.ConvertTag; }
                else if (column.Purpose == ColumnPurpose.Boolean) { converter = MsDataMapper.ConvertBoolean; }
                else if (column.Purpose == ColumnPurpose.Numeric) { converter = MsDataMapper.ConvertNumeric; type = SqlDbType.Decimal; }
                else if (column.Purpose == ColumnPurpose.DateTime) { converter = _convertDateTime; type = type = SqlDbType.DateTime2; }
                else if (column.Purpose == ColumnPurpose.String)
                {
                    converter = MsDataMapper.ConvertString;
                    
                    type = type = (column.Type.IsFixed) ? SqlDbType.NChar : SqlDbType.NVarChar;
                }
                else if (column.Purpose == ColumnPurpose.TypeCode) { converter = MsDataMapper.ConvertTypeCode; }
                else if (column.Purpose == ColumnPurpose.Identity) { converter = MsDataMapper.ConvertIdentity; }

                SqlMetaData metadata;

                if (type == SqlDbType.NChar)
                {
                    metadata = new SqlMetaData(column.Name, type, input.Size);
                }
                else if (type == SqlDbType.NVarChar)
                {
                    metadata = new SqlMetaData(column.Name, type, (input.Size == 0) ? -1 : input.Size);
                }
                else if (type == SqlDbType.Binary)
                {
                    metadata = new SqlMetaData(column.Name, type, input.Size);
                }
                else if (type == SqlDbType.VarBinary)
                {
                    metadata = new SqlMetaData(column.Name, type, -1);
                }
                else if (type == SqlDbType.Decimal)
                {
                    metadata = new SqlMetaData(column.Name, type, input.Precision, input.Scale);
                }
                else
                {
                    metadata = new SqlMetaData(column.Name, type);
                }

                columns.Add(metadata);

                _ordinals.Add(column, ordinal++);

                _converters.Add(column, converter);
            }
        }

        private static string CreateTypeStatement(in EntityDefinition metadata, in string name)
        {
            StringBuilder sql = new();

            sql.Append("CREATE TYPE").Append(' ').Append(name).Append(' ').Append("AS TABLE").Append(' ').Append('(');

            int count;
            bool first = true;
            ColumnDefinition column;
            List<ColumnDefinition> columns;

            foreach (PropertyDefinition property in metadata.Properties)
            {
                columns = property.Columns;

                if (columns is null || columns.Count == 0)
                {
                    continue;
                }

                count = property.Columns.Count;

                for (int i = 0; i < count; i++)
                {
                    column = columns[i];

                    if (column.IsGenerated)
                    {
                        continue;
                    }

                    if (!first) { sql.Append(',').Append(' '); }

                    sql.Append(column.Name).Append(' ').Append(MsSqlHelper.ToSqlDataType(column.Type));

                    if (column.IsPrimaryKey)
                    {
                        sql.Append(' ').Append("PRIMARY KEY");
                    }

                    first = false;
                }
            }

            sql.Append(')').Append(';');

            return sql.ToString();
        }
        private void TranspileInsertStatement()
        {
            string columns = TranspileColumns();

            StringBuilder sql = new();

            sql.Append("INSERT INTO ");
            sql.Append(_target.DbName).Append(' ').Append('(');
            sql.Append(columns);
            sql.Append(')').Append(' ').Append("SELECT").Append(' ');
            //TODO: NEXT VALUE FOR so_import OVER (ORDER BY order_column ASC)
            sql.Append(columns);
            sql.Append(' ').Append("FROM @stage_table ORDER BY order_column ASC;");

            _insertTable = sql.ToString();
        }
        private string TranspileColumns()
        {
            StringBuilder sql = new();

            int count;
            bool first = true;
            ColumnDefinition column;
            List<ColumnDefinition> columns;

            foreach (PropertyDefinition property in _target.Properties)
            {
                columns = property.Columns;

                if (columns is null || columns.Count == 0)
                {
                    continue;
                }

                count = property.Columns.Count;

                for (int i = 0; i < count; i++)
                {
                    column = columns[i];

                    if (column.IsGenerated)
                    {
                        continue;
                    }

                    if (!first) { sql.Append(',').Append(' '); }

                    sql.Append(column.Name);

                    first = false;
                }
            }

            return sql.ToString();
        }

        public override ExitCode Process()
        {
            if (_context.GetDataSource() is not MsDataSourceScope use)
            {
                throw new InvalidOperationException();
            }

            if (_context.GetValue(in _bufferName) is not List<DataObject> buffer)
            {
                throw new InvalidOperationException();
            }

            if (buffer.Count == 0)
            {
                return ExitCode.Success;
            }

            using (SqlCommand command = use.CreateCommand())
            {
                //command.CommandText = _createType;
                //command.CommandType = CommandType.Text;
                //command.CommandTimeout = 10; // seconds
                //command.ExecuteNonQuery();

                command.CommandText = _insertTable;
                command.CommandType = CommandType.Text;
                command.CommandTimeout = 600; // seconds
                SqlParameter tvp = new()
                {
                    ParameterName = "@stage_table",
                    SqlDbType = SqlDbType.Structured,
                    TypeName = "dbo.udt" + _target.DbName,
                    Value = Stream(buffer)
                };
                command.Parameters.Add(tvp);

                _nextRecord = 0;

                while (_nextRecord < buffer.Count)
                {
                    command.ExecuteNonQuery();
                }
            }

            //TODO; clear buffer-record data
            _context.SetValue(in _bufferItem, null);

            return ExitCode.Success;
        }

        private int _nextRecord;
        private IEnumerable<SqlDataRecord> Stream(List<DataObject> buffer)
        {
            while (_nextRecord < buffer.Count)
            {
                DataObject source = buffer[_nextRecord];

                _context.SetValue(in _bufferItem, source);

                SetDataRecordValues(in _record);

                _nextRecord++;
                
                yield return _record;

                if (_nextRecord % 100 == 0)
                {
                    break;
                }
            }
        }
        private void SetDataRecordValues(in SqlDataRecord record)
        {
            record.SetInt32(0, _nextRecord);

            int ordinal;
            object value;
            Func<object, object> converter;

            foreach (PropertyDefinition property in _target.Properties)
            {
                value = null; // default value

                if (_statement.TryGetMapping(property.Name, out ColumnExpression map))
                {
                    if (map.Expression is FunctionExpression function && function.Token == Token.VECTOR)
                    {
                        value = 0; // sequence next value
                    }
                    else
                    {
                        value = _context.Evaluate(map.Expression);
                    }
                }

                foreach (ColumnDefinition column in property.Columns)
                {
                    if (!_ordinals.TryGetValue(column, out ordinal))
                    {
                        continue; // database auto-generated column
                    }

                    converter = _converters[column];

                    value = converter(value);

                    record.SetValue(ordinal, value);
                }
            }
        }
        public override void Dispose()
        {
            // do nothing
        }
    }
}