using DaJet.Data;
using DaJet.Scripting.Model;
using DaJet.TypeSystem;
using Microsoft.Data.SqlClient;
using System.Data;

namespace DaJet.Scripting
{
    public sealed class MsBulkInsertProcessor : ProcessorBase
    {
        private readonly ScriptContext _context;
        private readonly InsertStatement _statement;
        private readonly EntityDefinition _target;
        private readonly int _yearOffset;
        private readonly string _bufferName;
        private readonly string _bufferItem;
        private readonly DataTable _table = new();
        private readonly Dictionary<ColumnDefinition, DataColumn> _map = new();
        private readonly Dictionary<ColumnDefinition, Func<object, object>> _converters = new();
        public MsBulkInsertProcessor(in ScriptContext context, in InsertStatement statement)
        {
            if (context.GetDataSource() is not MsDataSourceScope)
            {
                throw new InvalidOperationException();
            }
            
            _context = context;
            _statement = statement;
            _yearOffset = statement.YearOffset;

            if (_statement.Target is not TableReference table || table.Binding is not EntityDefinition target)
            {
                throw new InvalidOperationException();
            }

            if (_statement.Source is not VariableReference variable
                || variable.Binding is not DeclareStatement declare
                || !(declare.Type.IsArray && declare.Type.IsObject))
            {
                throw new InvalidOperationException();
            }

            _target = target;

            _bufferName = variable.Identifier;
            _bufferItem = string.Format("{0}{1}", _bufferName, "_Item");
            
            _context.CreateVariable(in _bufferItem);
            
            PrepareDataTable();
        }
        private void PrepareDataTable()
        {
            PropertyDefinition property;
            List<PropertyDefinition> properties = _target.Properties;

            for (int p = 0; p < properties.Count; p++)
            {
                property = properties[p];

                PrepareColumns(in property);
            }
        }
        private void PrepareColumns(in PropertyDefinition property)
        {
            if (_statement.TryGetMapping(property.Name, out ColumnExpression map))
            {
                if (map.Expression is FunctionExpression function && function.Token == Token.VECTOR)
                {
                    ColumnDefinition column = property.Columns[0];

                    DataColumn target = new()
                    {
                        DataType = typeof(int),
                        ColumnName = column.Name
                    };

                    _map.Add(column, target);

                    _table.Columns.Add(target);

                    _converters.Add(column, GetRowNumber);

                    return; // generated by SEQUENCE
                }
                else if (map.Expression is MemberAccessExpression member && member.GetVariableName() == _bufferName)
                {
                    member.Identifier = member.Identifier.Replace(_bufferName, _bufferItem);
                }
            }
            
            foreach (ColumnDefinition column in property.Columns)
            {
                if (column.IsGenerated)
                {
                    continue; // database auto-generated column
                }

                Type type = typeof(byte[]);
                DataType source = column.Type;
                Func<object, object> converter = null;

                DataColumn target = new()
                {
                    ColumnName = column.Name
                };
                
                if (column.Purpose == ColumnPurpose.Value)
                {
                    if (source.IsBoolean) { converter = MsDataMapper.ConvertBoolean; }
                    else if (source.IsDecimal) { converter = MsDataMapper.ConvertNumeric; type = typeof(decimal); }
                    else if (source.IsDateTime) { converter = GetDateTime; type = typeof(DateTime); }
                    else if (source.IsString) { converter = MsDataMapper.ConvertString; type = typeof(string); }
                    else if (source.IsBinary)
                    {
                        if (property.Type.IsUuid) //TODO: select converter comparing property type to desired column type
                        {
                            converter = MsDataMapper.ConvertUuid;
                        }
                        else
                        {
                            converter = MsDataMapper.ConvertBinary;
                        }
                    }
                    else if (source.IsUuid) { converter = MsDataMapper.ConvertUuid; }
                    else if (source.IsEntity) { converter = MsDataMapper.ConvertIdentity; }
                }
                else if (column.Purpose == ColumnPurpose.Tag) { converter = MsDataMapper.ConvertTag; }
                else if (column.Purpose == ColumnPurpose.TypeCode) { converter = MsDataMapper.ConvertTypeCode; }
                else if (column.Purpose == ColumnPurpose.Identity) { converter = MsDataMapper.ConvertIdentity; }
                else if (column.Purpose == ColumnPurpose.Boolean) { converter = MsDataMapper.ConvertBoolean; }
                else if (column.Purpose == ColumnPurpose.Numeric) { converter = MsDataMapper.ConvertNumeric; type = typeof(decimal); }
                else if (column.Purpose == ColumnPurpose.DateTime) { converter = GetDateTime; type = typeof(DateTime); }
                else if (column.Purpose == ColumnPurpose.String) { converter = MsDataMapper.ConvertString; type = typeof(string); }

                target.DataType = type;

                _map.Add(column, target);

                _table.Columns.Add(target);

                _converters.Add(column, converter);
            }
        }
        private object GetDateTime(object value)
        {
            return MsDataMapper.ConvertDateTime(value, _yearOffset);
        }
        private object GetRowNumber(object value)
        {
            return _table.Rows.Count;
        }
        private void SetRowValues(in DataRow row)
        {
            foreach (PropertyDefinition property in _target.Properties)
            {
                object value = null; // default value

                if (_statement.TryGetMapping(property.Name, out ColumnExpression map))
                {
                    if (map.Expression is FunctionExpression function && function.Token == Token.VECTOR)
                    {
                        value = 0; //TODO: row sequence number
                    }
                    else
                    {
                        value = _context.Evaluate(map.Expression);
                    }
                }

                foreach (ColumnDefinition column in property.Columns)
                {
                    if (!_map.TryGetValue(column, out DataColumn target))
                    {
                        continue; // database auto-generated column
                    }

                    row[target] = _converters[column](value);
                }
            }
        }
        public override ExitCode Process()
        {
            if (_context.GetDataSource() is not MsDataSourceScope use)
            {
                throw new InvalidOperationException();
            }

            if (_context.GetValue(in _bufferName) is not List<DataObject> buffer)
            {
                throw new InvalidOperationException();
            }

            if (buffer.Count == 0)
            {
                return ExitCode.Success;
            }

            _table.Rows.Clear();

            foreach (DataObject record in buffer)
            {
                _context.SetValue(in _bufferItem, record);

                DataRow row = _table.NewRow();

                _table.Rows.Add(row);

                SetRowValues(in row);
            }

            _context.SetValue(in _bufferItem, null);

            SqlBulkCopyOptions options = SqlBulkCopyOptions.Default; // TableLock CacheMetadata

            try
            {
                using (SqlBulkCopy insert = new(use.Connection, options, use.Transaction))
                {
                    insert.BulkCopyTimeout = 600;

                    insert.DestinationTableName = _target.DbName;

                    foreach (var mapping in _map)
                    {
                        insert.ColumnMappings.Add(mapping.Key.Name, mapping.Value.ColumnName);
                    }

                    //TODO: insert.ColumnOrderHints

                    insert.WriteToServer(_table);
                    
                    // int count = insert.RowsCopied;
                }
            }
            catch
            {
                throw;
            }
            finally
            {
                _table.Rows.Clear();
            }
            
            return ExitCode.Success;
        }
        public override void Dispose()
        {
            // do nothing
        }
        
        //internal override IEnumerable<ConfigFileBuffer> Stream(string tableName, string[] fileNames)
        //{
        //    using (SqlConnection connection = new(_connectionString))
        //    {
        //        connection.Open();

        //        using (SqlCommand command = connection.CreateCommand())
        //        {
        //            command.CommandText = "CREATE TABLE #ConfigFileNames (FileName nvarchar(128) NOT NULL);";
        //            command.CommandType = CommandType.Text;
        //            command.CommandTimeout = 10; // seconds
        //            command.ExecuteNonQuery();

        //            using (SqlBulkCopy insert = new(connection))
        //            {
        //                insert.DestinationTableName = "#ConfigFileNames";
        //                DataTable table = CreateFileNamesTable(in fileNames);
        //                insert.WriteToServer(table);
        //            }

        //            command.CommandText = tableName == ConfigTables.Config
        //                ? MS_CONFIG_STREAM_SCRIPT
        //                : MS_CONFIG_CAS_STREAM_SCRIPT;

        //            command.CommandType = CommandType.Text;
        //            command.CommandTimeout = 60; // seconds

        //            using (SqlDataReader reader = command.ExecuteReader())
        //            {
        //                while (reader.Read())
        //                {
        //                    using (ConfigFileBuffer buffer = new(reader))
        //                    {
        //                        yield return buffer;
        //                    }
        //                }
        //                reader.Close();
        //            }
        //        }
        //    }
        //}
    }
}

//CREATE TABLE #test
//(
//   НомерСообщения int PRIMARY KEY,
//   ТелоСообщения nvarchar(10)
//);

//INSERT #test WITH (TABLOCK) VALUES (1, N'test 1'), (2, N'test 2'), (3, N'test 3');

//SELECT NEXT VALUE FOR so_import OVER (ORDER BY НомерСообщения), ТелоСообщения FROM #test;

//DROP TABLE #test;