<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DaJet.Scripting</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>DaJet.Scripting</AssemblyName>
    <Version>2.0.7</Version>
    <Authors>Zhichkin</Authors>
    <Description>DaJet Script - SQL-like language for data integration and stream processing</Description>
    <Copyright>Zhichkin © 2020</Copyright>
    <PackageProjectUrl>https://zhichkin.github.io/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/zhichkin/dajet-scripting</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Title>DaJet.Scripting</Title>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DaJet.Metadata" Version="5.0.23" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="transformer\" />
  </ItemGroup>

</Project>
